<a href="https://colab.research.google.com/github/ustab/Ansible-Notes/blob/master/Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("https://data.cms.gov/provider-data/sites/default/files/resources/17fcbee365b92b458e5b0a78005d5511_1649361914/Inpatient_Rehabilitation_Facility-Conditions_Mar2022.csv")
df

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Condition,Count,Footnote
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,All other conditions,346,NaN
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain disease or condition (non-traumatic),150,NaN
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain injury (traumatic),38,NaN
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Hip or femur fracture,156,NaN
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,"Hip or knee replacement, amputation or other b...",329,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10750,713028,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,8650 MILLICENT WAY,NaN,SHREVEPORT,LA,71115,Caddo,(318) 642-8100,6,"Hip or knee replacement, amputation or other b...",Not Available,2.0
10751,713028,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,8650 MILLICENT WAY,NaN,SHREVEPORT,LA,71115,Caddo,(318) 642-8100,6,Nervous system disorder (excluding stroke),Not Available,2.0
10752,713028,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,8650 MILLICENT WAY,NaN,SHREVEPORT,LA,71115,Caddo,(318) 642-8100,6,Spinal cord disease or condition (non-traumatic),Not Available,2.0
10753,713028,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,8650 MILLICENT WAY,NaN,SHREVEPORT,LA,71115,Caddo,(318) 642-8100,6,Spinal cord injury (traumatic),Not Available,2.0
10754,713028,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,8650 MILLICENT WAY,NaN,SHREVEPORT,LA,71115,Caddo,(318) 642-8100,6,Stroke,Not Available,2.0

In [4]:
df.head()

,CMS Certification Number (CCN),Facility Name,Address Line 1,Address Line 2,City,State,Zip Code,County Name,Phone Number,CMS Region,Condition,Count,Footnote
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,All other conditions,346,NaN
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain disease or condition (non-traumatic),150,NaN
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Brain injury (traumatic),38,NaN
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,Hip or femur fracture,156,NaN
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,NaN,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,"Hip or knee replacement, amputation or other b...",329,NaN

In [5]:
df.describe()

           Zip Code    CMS Region     Footnote
count  10755.000000  10755.000000  4484.000000
mean   53596.402510      5.372385     1.342328
std    26842.053422      2.163951     0.474542
min      674.000000      1.000000     1.000000
25%    31792.000000      4.000000     1.000000
50%    53405.000000      5.000000     1.000000
75%    76712.000000      6.000000     2.000000
max    99508.000000     10.000000     2.000000

In [6]:
df.shape

(10755, 13)

In [11]:
pd.read_html("https://www.cdc.gov/ncbddd/index.html")

ValueError: ignored